apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: web-app-staging

namespace: staging

resources:
- namespace.yaml
- ../../base

namePrefix: staging-

commonLabels:
  environment: staging
  tier: non-production

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml

replicas:
- name: web-app
  count: 1

