apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-yaml
data:
  database_host: "mysql-service"
  database_port: "3306"

  nginx.conf: |
    server {
      listen 80;
      location / {
        root /usr/share/nginx/html;
      }
    }

  app-config.json: |
    {
      "env": "production",
      "cache": true
    }
